// <auto-generated />
using Reporte.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Reporte.Migrations
{
  [DbContext(typeof(AppDbContext))]
  partial class AppDbContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

      modelBuilder.Entity("Reporte.Models.Person", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<string>("Apellido")
                      .IsRequired()
                      .HasColumnType("TEXT");

            b.Property<string>("Nombre")
                      .IsRequired()
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("Persons");
          });
#pragma warning restore 612, 618
    }
  }
}
